// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicConnect.Models;

public partial class Admin
{
    public int AdminId { get; set; }


    [Required(ErrorMessage = "Email is required.")]
    [EmailAddress(ErrorMessage = "Invalid email format.")]
    public string AdminEmail { get; set; }

    [Required(ErrorMessage = "Password is required.")]
    [DataType(DataType.Password)]
    public byte[] Password { get; set; }

    [NotMapped]
    public string UserPassword {  get; set; }

    public string SecurityQuestion { get; set; }

    public string SecurityAnswer { get; set; }
}