// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicConnect.Models;

public partial class BillingMedicine
{
    public int BillingId { get; set; }

    public int MedId { get; set; }

    public int Quantity { get; set; }

    public decimal? Tax { get; set; }

    public decimal? Discount { get; set; }

    public virtual Billing Billing { get; set; }

    public virtual Medicine Med { get; set; }
}