// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicConnect.Models;

public partial class Billing
{
    public int BillingId { get; set; }

    public int? PatientId { get; set; }

    public decimal? Tax { get; set; }

    public decimal? Discount { get; set; }

    public decimal? TotalPrice { get; set; }

    public virtual ICollection<BillingMedicine> BillingMedicines { get; set; } = new List<BillingMedicine>();

    public virtual Patient Patient { get; set; }
}