// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicConnect.Models;

public partial class Doctor
{
    public int DoctorId { get; set; }

    public string DoctorEmail { get; set; }

    public byte[] Password { get; set; }

    [NotMapped]
    public string UserPassword { get; set; }

    public string DoctorName { get; set; }

    public long? DoctorPhoneNo { get; set; }

    public string Specialization { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<DoctorAvailability> DoctorAvailabilities { get; set; } = new List<DoctorAvailability>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}