// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicConnect.Models;

public partial class FrontOffice
{
    public int FrontOfficeMemberCode { get; set; }

    public string FrontOfficeName { get; set; }

    public byte[] Password { get; set; }

    [NotMapped]
    public string UserPassword {  get; set; }
    public string FrontOfficeEmail { get; set; }

    public long? FrontOfficePhoneNo { get; set; }

    public string FrontOfficeAddress { get; set; }
}