// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicConnect.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int? PatientId { get; set; }

    public int? DoctorId { get; set; }

    public int? AppointmentId { get; set; }

    public string PatientMessage { get; set; }

    public string DoctorMessage { get; set; }

    public DateTime? SentDate { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Patient Patient { get; set; }
}