// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicConnect.Models;

public partial class Patient
{
    public int PatientId { get; set; }

    public string PatientEmail { get; set; }

    public byte[] Password { get; set; }

    [NotMapped]
    public string UserPassword { get; set; }
    public string PatientGender { get; set; }

    public string PatientName { get; set; }

    public int? PatientAge { get; set; }

    public DateTime? Dob { get; set; }

    public long? PatientPhoneNo { get; set; }

    public string PatientAddress { get; set; }

    public DateTime? PregisterDate { get; set; }

    public string SecurityQuestion { get; set; }

    public string SecurityAnswer { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Billing> Billings { get; set; } = new List<Billing>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}