// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicConnect.Models;

public partial class Pharmacist
{
    public int PharmMemberId { get; set; }

    public string PharmName { get; set; }

    public byte[] Password { get; set; }

    [NotMapped]
    public string UserPassword { get; set; }

    public string PharmEmail { get; set; }

    public long? PharmPhoneNo { get; set; }

    public string PharmAddress { get; set; }

    public virtual ICollection<Medicine> Medicines { get; set; } = new List<Medicine>();
}